title: Ashes Born's Blog
subtitle: 心中有座观澜阁，土木付炬皆尘生
description: Work & Life & learn
keywords: 'fornt-end,react,node,raspberry,Linux,docker,java,javascript,algorithm'
author: Ashes Born
language: zh en
timezone: Asia/ShangHai
url: 'http://sadofriod.github.io'
root: /
permalink: ':title.html'
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: icarus
deploy:
  type: git
  repo: 'https://github.com/sadofriod/sadofriod.github.io.git'
  branch: master
feed:
  enable: true
  type: rss2
  path: rss2.xml
  limit: 140
  hub: null
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: '-date'
  icon: 'https://avatars.githubusercontent.com/u/23006024?v=4'
  autodiscovery: true
disqus_shortname: ashess-blog
math:
  engine: mathjax
  mathjax:
    src: >-
      https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML
markdown:
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-abbr
    - markdown-it-emoji
    - hexo-math
toc:
  maxDepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: '#'
    style: header-anchor
sitemap:
  path: google_sitemap.xml
baidusitemap:
  path: baidusitemap.xml
